import Head from "next/head";

import { FC } from "react";
import KanbanBoard from "../components/KanbanBoard/KanbanBoard";

import Navbar from "../components/Navbar/Navbar";
import styles from "../styles/Home.module.css";
import useKanban from "../hooks/useKanban/useKanban";

export default function Home() {
  const kanban = useKanban();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar>
        <h1>Merlin - Kanban Code Test</h1>
      </Navbar>

      <div style={{ width: "100%", display: "flex", justifyContent: "center" }}>
        <KanbanBoard {...kanban} />
      </div>
    </div>
  );
}

const Button: FC<{ onClick: () => void }> = ({ children, onClick }) => {
  return <button onClick={onClick}>{children}</button>;
};
